# Generated by Django 4.1.5 on 2023-01-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('personaje', models.CharField(max_length=50)),
                ('cc', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
            ],
        ),
    ]
