# Generated by Django 4.1.5 on 2023-01-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_alter_curso_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='curso',
            new_name='Company',
        ),
    ]
